[programs.localnet]
anchor_programs = "FA1jq7srnPM7GzyXtUhXfxmTsmoaUgccWyVUWhTRH7zn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "https://rpc-mainnet-fork.dappio.xyz"
cluster = "localnet"
# cluster = "https://api.devnet.solana.com"

wallet = "/Users/macbookpro4eric/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
